/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xprodswing.principal;

import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mi
 */
public class Commande extends javax.swing.JFrame {

    /**
     * Creates new form Commande
     */
    public Commande() {
        initComponents();
        this.setTitle("XProd gestion des commandes - Administrateur");
        setLocationRelativeTo(null);  //Pour centrer le contenu de ma fenêtre
        tableUpdate();  //Mettre à jour la table des produits
        tableUpdateClient();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItemAddFournisseur = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItemAddCommande = new javax.swing.JMenuItem();
        jMenuAdminUser = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePRODUIT = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCLIENT = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtREFCLIENT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDESIGNATIONCLIENT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDESCRIPTIFCLIENT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPRIXUHTCLIENT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtQTECLIENT = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPRENOMCLIENT = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNOMCLIENT = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPRIXTHTCCLIENT = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtBILL = new javax.swing.JTextArea();
        btnCREATEBILL = new javax.swing.JButton();
        btnPRINTBILL = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableCOMMANDE = new javax.swing.JTable();
        btnADDCOMMANDE = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtPRIXTTCCLIENT = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTVACLIENT = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtFRAISPORT = new javax.swing.JTextField();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenuItemAddFournisseur2 = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        jMenuItemAddCommande2 = new javax.swing.JMenuItem();
        jMenuAdminUser1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItemManageClient = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Fournisseur");

        jMenuItemAddFournisseur.setText("Ajouter  un  fournisseur");
        jMenuItemAddFournisseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddFournisseurActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemAddFournisseur);

        jMenuBar2.add(jMenu5);

        jMenu8.setText("Commande");

        jMenuItemAddCommande.setText("Ajouter  une  commande ");
        jMenuItemAddCommande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddCommandeActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItemAddCommande);

        jMenuBar2.add(jMenu8);

        jMenuAdminUser.setText("Utilisateurs");
        jMenuAdminUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAdminUserActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Gestion des utilisateurs");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuAdminUser.add(jMenuItem2);

        jMenuBar2.add(jMenuAdminUser);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setText("GESTION DES COMMANDES");

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mi\\Documents\\NetBeansProjects\\Saved\\XprodSwing01\\src\\Images\\logo_small.jpeg")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(433, 433, 433)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(290, 290, 290))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LISTE DES PRODUITS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13), new java.awt.Color(255, 255, 255))); // NOI18N

        jScrollPane1.setBackground(new java.awt.Color(0, 102, 153));

        tablePRODUIT.setForeground(new java.awt.Color(0, 102, 153));
        tablePRODUIT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID PRODUIT", "REF", "DESIGNATION", "DESCRIPTIF", "PRIX UHT"
            }
        ));
        tablePRODUIT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePRODUITMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePRODUIT);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(0, 102, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LISTE DES CLIENTS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13), new java.awt.Color(255, 255, 255))); // NOI18N

        tableCLIENT.setForeground(new java.awt.Color(0, 102, 153));
        tableCLIENT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PRENOM", "NOM", "ADRESSE", "CP", "VILLE", "PAYS", "TEL", "MOBILE", "EMAIL"
            }
        ));
        tableCLIENT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCLIENTMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableCLIENT);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(0, 102, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LIGNE DE COMMANDE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PRENOM CLIENT :");

        txtREFCLIENT.setForeground(new java.awt.Color(0, 102, 153));
        txtREFCLIENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtREFCLIENTActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" DESIGNATION :");

        txtDESIGNATIONCLIENT.setForeground(new java.awt.Color(0, 102, 153));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DESCRIPTIF :");

        txtDESCRIPTIFCLIENT.setForeground(new java.awt.Color(0, 102, 153));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PRIX THT :");

        txtPRIXUHTCLIENT.setForeground(new java.awt.Color(0, 102, 153));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("QTE :");

        txtQTECLIENT.setForeground(new java.awt.Color(0, 102, 153));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("REF :");

        txtPRENOMCLIENT.setForeground(new java.awt.Color(0, 102, 153));
        txtPRENOMCLIENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPRENOMCLIENTActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("NOM CLIENT :");

        txtNOMCLIENT.setForeground(new java.awt.Color(0, 102, 153));
        txtNOMCLIENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNOMCLIENTActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("PRIX  UHT :");

        txtPRIXTHTCCLIENT.setForeground(new java.awt.Color(0, 102, 153));

        txtBILL.setColumns(20);
        txtBILL.setRows(5);
        jScrollPane4.setViewportView(txtBILL);

        btnCREATEBILL.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCREATEBILL.setForeground(new java.awt.Color(0, 102, 153));
        btnCREATEBILL.setText("Créer la facture");
        btnCREATEBILL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCREATEBILLActionPerformed(evt);
            }
        });

        btnPRINTBILL.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPRINTBILL.setForeground(new java.awt.Color(0, 102, 153));
        btnPRINTBILL.setText("Imprimer la facture");
        btnPRINTBILL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPRINTBILLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPRENOMCLIENT, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtREFCLIENT))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel12)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtQTECLIENT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(txtPRIXUHTCLIENT, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDESCRIPTIFCLIENT, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDESIGNATIONCLIENT, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPRIXTHTCCLIENT)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNOMCLIENT)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnCREATEBILL, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPRINTBILL, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPRENOMCLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNOMCLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtREFCLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDESIGNATIONCLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDESCRIPTIFCLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPRIXUHTCLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtQTECLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPRIXTHTCCLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCREATEBILL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPRINTBILL, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 102, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "COMMANDE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13), new java.awt.Color(255, 255, 255))); // NOI18N

        jScrollPane3.setBackground(new java.awt.Color(0, 102, 153));

        tableCOMMANDE.setForeground(new java.awt.Color(0, 102, 153));
        tableCOMMANDE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID PRODUIT", "REF", "DESIGNATION", "DESCRIPTIF", "PRIX UHT", "QTE", "PRIX THT"
            }
        ));
        tableCOMMANDE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCOMMANDEMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableCOMMANDE);

        btnADDCOMMANDE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnADDCOMMANDE.setForeground(new java.awt.Color(0, 102, 153));
        btnADDCOMMANDE.setText("Valider la commande");
        btnADDCOMMANDE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDCOMMANDEActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PRIX TTC :");

        txtPRIXTTCCLIENT.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtPRIXTTCCLIENT.setForeground(new java.awt.Color(0, 102, 153));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("T.V.A");

        txtTVACLIENT.setForeground(new java.awt.Color(0, 102, 153));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("FRAIS DE PORT :");

        txtFRAISPORT.setForeground(new java.awt.Color(0, 102, 153));
        txtFRAISPORT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFRAISPORTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(txtFRAISPORT, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(114, 114, 114)
                                .addComponent(txtTVACLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtPRIXTTCCLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(btnADDCOMMANDE, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFRAISPORT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTVACLIENT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnADDCOMMANDE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtPRIXTTCCLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jMenu11.setText("File");
        jMenuBar4.add(jMenu11);

        jMenu12.setText("Edit");
        jMenuBar4.add(jMenu12);

        jMenu13.setText("Fournisseur");

        jMenuItemAddFournisseur2.setText("Ajouter  un  fournisseur");
        jMenuItemAddFournisseur2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddFournisseur2ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItemAddFournisseur2);

        jMenuBar4.add(jMenu13);

        jMenu14.setText("Commande");

        jMenuItemAddCommande2.setText("Ajouter  une  commande ");
        jMenuItemAddCommande2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddCommande2ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItemAddCommande2);

        jMenuBar4.add(jMenu14);

        jMenuAdminUser1.setText("Utilisateurs");
        jMenuAdminUser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAdminUser1ActionPerformed(evt);
            }
        });

        jMenuItem3.setText("Gestion des utilisateurs");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuAdminUser1.add(jMenuItem3);

        jMenuItemManageClient.setText("Gestion des clients");
        jMenuItemManageClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemManageClientActionPerformed(evt);
            }
        });
        jMenuAdminUser1.add(jMenuItemManageClient);

        jMenuBar4.add(jMenuAdminUser1);

        setJMenuBar(jMenuBar4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAddFournisseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddFournisseurActionPerformed
        //Ajout d'un nouveau fournisseur

        Fournisseur newFour  = new Fournisseur();
        newFour.setVisible(true);
    }//GEN-LAST:event_jMenuItemAddFournisseurActionPerformed

    private void jMenuItemAddCommandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddCommandeActionPerformed
        //Ajouter une nouvelle commande
        Commande newCmd = new Commande();
        newCmd.setVisible(true);
    }//GEN-LAST:event_jMenuItemAddCommandeActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        AdminUser newAdminUser = new AdminUser();
        newAdminUser.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuAdminUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAdminUserActionPerformed

    }//GEN-LAST:event_jMenuAdminUserActionPerformed

     //Connection
    Connection con;
    PreparedStatement pst; 
    
    //Mise à jour tableau
    private void tableUpdate(){
    
        int cpt;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/xproddb", "root", ""); 
            pst = con.prepareStatement("SELECT * FROM produits"); 
            ResultSet rs = pst.executeQuery();
            
            ResultSetMetaData rsmd = rs.getMetaData();
            cpt = rsmd.getColumnCount();
            DefaultTableModel dtm =(DefaultTableModel)tablePRODUIT.getModel();
            dtm.setRowCount(0);
            
            while(rs.next()){
            Vector vect = new Vector();
            
            for(int i=1; i<= cpt; i++ ){
            vect.add(rs.getString("IDPRODUIT"));
            vect.add(rs.getString("REF"));
            vect.add(rs.getString("DESIGNATION"));
            vect.add(rs.getString("DESCRIPTIF"));
            vect.add(rs.getString("PRIXUHT"));
            
                    }
            dtm.addRow(vect); 
            }
             
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(XprodDesktopAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(XprodDesktopAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
      //Mise à jour tableau
    private void tableUpdateClient(){
    
        int cpt;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/xproddb", "root", ""); 
            pst = con.prepareStatement("SELECT * FROM clients"); 
            ResultSet rs = pst.executeQuery();
            
            ResultSetMetaData rsmd = rs.getMetaData();
            cpt = rsmd.getColumnCount();
            DefaultTableModel dtm =(DefaultTableModel)tableCLIENT.getModel();
            dtm.setRowCount(0);
            
            while(rs.next()){
            Vector vect = new Vector();
            
            for(int i=1; i<= cpt; i++ ){
            vect.add(rs.getString("IDCLIENT"));
            vect.add(rs.getString("PRENOM"));
            vect.add(rs.getString("NOM"));
            vect.add(rs.getString("ADRESSE"));
            vect.add(rs.getString("CP"));
             vect.add(rs.getString("VILLE"));
            vect.add(rs.getString("PAYS"));
            vect.add(rs.getString("TEL"));
            vect.add(rs.getString("MOBILE"));
            vect.add(rs.getString("EMAIL"));
                    }
            dtm.addRow(vect); 
            }
             
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(XprodDesktopAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(XprodDesktopAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void tablePRODUITMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePRODUITMouseClicked
 // Pour selectionner les informations d'un champ
        double sum = 0.0; 
        double totalTTC = 0.0;
        double prixTVA=0.0;
        DefaultTableModel dtm = (DefaultTableModel)tablePRODUIT.getModel();
        int selectedIndex = tablePRODUIT.getSelectedRow();
        //Préremplir les champs de texte
        txtREFCLIENT.setText(dtm.getValueAt(selectedIndex, 1).toString());
        txtDESIGNATIONCLIENT.setText(dtm.getValueAt(selectedIndex, 2).toString());
        txtDESCRIPTIFCLIENT.setText(dtm.getValueAt(selectedIndex, 3).toString());
        txtPRIXUHTCLIENT.setText(dtm.getValueAt(selectedIndex, 4).toString()); 
               
        //Ajout dans la table des commandes
        String idCLIENT = dtm.getValueAt(selectedIndex, 0).toString();
        String txtREFCLIENT = dtm.getValueAt(selectedIndex, 1).toString();
        String txtDESIGNATIONCLIENT = dtm.getValueAt(selectedIndex, 2).toString();
        String  txtDESCRIPTIFCLIENT = dtm.getValueAt(selectedIndex, 3).toString();
        double txtPRIXUHTCLIENT = Double.parseDouble(dtm.getValueAt(selectedIndex, 4).toString());
        
         int qte = Integer.parseInt(JOptionPane.showInputDialog(null,"Entrez la quantité !"));      
            
         double tot = txtPRIXUHTCLIENT * qte;
         double fraisPort = Integer.parseInt(JOptionPane.showInputDialog(null,"Entrez les frais de port !")); 
         int tva = Integer.parseInt(JOptionPane.showInputDialog(null,"Entrez la TVA exemple 20 !"));
         dtm = (DefaultTableModel)tableCOMMANDE.getModel();
             
            dtm.addRow(new Object[]          
            {
              idCLIENT,
              txtREFCLIENT,
              txtDESIGNATIONCLIENT,
              txtDESCRIPTIFCLIENT,
              txtPRIXUHTCLIENT,
              qte,
              tot
             }        
            );    
        
    for(int i=0; i<tableCOMMANDE.getRowCount(); i++)
     {
 
    sum = fraisPort + sum + Double.parseDouble(tableCOMMANDE.getValueAt((int)i,6).toString());  //6 colonnes dans la table des commandes
    prixTVA = sum*tva/100 ;
    totalTTC = sum + sum*tva/100 ;
     } 
        txtPRIXTTCCLIENT.setText(Double.toString(totalTTC));
        txtQTECLIENT.setText(Integer.toString(qte));
        txtPRIXTHTCCLIENT.setText(Double.toString(tot));
        txtFRAISPORT.setText(Double.toString(fraisPort));
        txtTVACLIENT.setText(Double.toString(prixTVA));
    }//GEN-LAST:event_tablePRODUITMouseClicked

    private void jMenuItemAddFournisseur2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddFournisseur2ActionPerformed
        //Ajout d'un nouveau fournisseur

        Fournisseur newFour  = new Fournisseur();
        newFour.setVisible(true);
    }//GEN-LAST:event_jMenuItemAddFournisseur2ActionPerformed

    private void jMenuItemAddCommande2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddCommande2ActionPerformed
        //Ajouter une nouvelle commande
        Commande newCmd = new Commande();
        newCmd.setVisible(true);
    }//GEN-LAST:event_jMenuItemAddCommande2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        AdminUser newAdminUser = new AdminUser();
        newAdminUser.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItemManageClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemManageClientActionPerformed
        Client newClient = new Client();
        newClient.setVisible(true);
    }//GEN-LAST:event_jMenuItemManageClientActionPerformed

    private void jMenuAdminUser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAdminUser1ActionPerformed

    }//GEN-LAST:event_jMenuAdminUser1ActionPerformed

    private void txtREFCLIENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtREFCLIENTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtREFCLIENTActionPerformed

    private void txtPRENOMCLIENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPRENOMCLIENTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPRENOMCLIENTActionPerformed

    private void btnADDCOMMANDEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDCOMMANDEActionPerformed
        // Ajout fournisseur
        String refCLIENT = txtREFCLIENT.getText();
        String designationCLIENT = txtDESIGNATIONCLIENT.getText();
        String descriptifCLIENT = txtDESCRIPTIFCLIENT.getText();
        String prixuhtCLIENT = txtPRIXUHTCLIENT.getText();
        String qteCLIENT = txtQTECLIENT.getText();
        String tvaCLIENT = txtTVACLIENT.getText();
        String prixttcCLIENT = txtPRIXTTCCLIENT.getText();
        String infosCLIENT = txtPRENOMCLIENT.getText();
       

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/xproddb","root","");
            pst = con.prepareStatement("insert into commande(PRENOM,NOM,EMAIL,"
                + "CP,VILLE,PAYS,TEL,MOBILE)values(?,?,?,?,?,?,?,?,?)");
            pst.setString(1, refCLIENT);
            pst.setString(2, designationCLIENT);
            pst.setString(3, descriptifCLIENT);
            pst.setString(4, prixuhtCLIENT);
            pst.setString(5, qteCLIENT);
            pst.setString(6, tvaCLIENT);
            pst.setString(7, prixttcCLIENT);
            pst.setString(8, infosCLIENT);
            

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Données enregistrées !");
            tableUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnADDCOMMANDEActionPerformed

    private void txtNOMCLIENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNOMCLIENTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNOMCLIENTActionPerformed

    private void txtFRAISPORTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFRAISPORTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFRAISPORTActionPerformed

    private void tableCLIENTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCLIENTMouseClicked
        // Pour selectionner les informations d'un champ
        DefaultTableModel dtm = (DefaultTableModel)tableCLIENT.getModel();
        int selectedIndex = tableCLIENT.getSelectedRow();
        
        txtPRENOMCLIENT.setText(dtm.getValueAt(selectedIndex, 1).toString());
        txtNOMCLIENT.setText(dtm.getValueAt(selectedIndex, 2).toString());
        
        
    }//GEN-LAST:event_tableCLIENTMouseClicked

    private void tableCOMMANDEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCOMMANDEMouseClicked
         
      
    }//GEN-LAST:event_tableCOMMANDEMouseClicked

    private void btnCREATEBILLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCREATEBILLActionPerformed
        // Create bill
         double totalTTC = Double.parseDouble(txtPRIXTTCCLIENT.getText());
         double tva = Double.parseDouble(txtTVACLIENT.getText());
         double fraisPORT = Double.parseDouble(txtFRAISPORT.getText());
         String prenomClient = txtPRENOMCLIENT.getText();
         String nomClient = txtNOMCLIENT.getText();
        
          DefaultTableModel model = new DefaultTableModel();
        
        model = (DefaultTableModel)tableCOMMANDE.getModel();
        
         txtBILL.setText(txtBILL.getText() + "**********************************************************************************\n");
         txtBILL.setText(txtBILL.getText() + "                            FACTURE XPROD                                         \n");
         txtBILL.setText(txtBILL.getText() + "**********************************************************************************\n");
         //Names
         txtBILL.setText(txtBILL.getText() + "\t" + "\t" + "Prénom du client : " + prenomClient + "\n");
         txtBILL.setText(txtBILL.getText() + "\t" + "\t" + "Nom du client :    " + nomClient + "\n");
         
         //Heading
          txtBILL.setText(txtBILL.getText() + "REF " + "\t" + "DESIGNATION " + "\t" + "DESCRIPTIF " + "\t" + "PRIX UHT" + "\t" + "QTE" + "\t" + "PRIXTHT"+ "\n"  );
          
          for(int i = 0; i < model.getRowCount(); i++)
          {
              
              String ref = (String)model.getValueAt(i, 1);
              String design = (String)model.getValueAt(i, 2);
              String descr = (String)model.getValueAt(i, 3);
              
              double prixU = (double)model.getValueAt(i, 4);
              int qte = (int)model.getValueAt(i, 5);
              double prixTHT = (double)model.getValueAt(i, 6);
              
              
           txtBILL.setText(txtBILL.getText() + ref  + "\t" + design + "\t" + descr+ "\t" +  prixU  + "\t" + qte + "\t" + prixTHT  + "\n"  );
    
          }
          
          txtBILL.setText(txtBILL.getText() + "\n");    
           
          txtBILL.setText(txtBILL.getText() + "\t" + "\t" + "Frais port : " + fraisPORT + "\n");
          txtBILL.setText(txtBILL.getText() + "\t" + "\t" + "TVA : " + tva + "\n");
          txtBILL.setText(txtBILL.getText() + "\t" + "\t" + "Total TTC : " + totalTTC + "\n");
          txtBILL.setText(txtBILL.getText() + "\n");
          txtBILL.setText(txtBILL.getText() + "*******************************************************\n");
          txtBILL.setText(txtBILL.getText() + "           MERCI POUR VOTRE VISITE ! A BIENTOT!            \n");
          
          
    }//GEN-LAST:event_btnCREATEBILLActionPerformed

    private void btnPRINTBILLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPRINTBILLActionPerformed
        try {
            //Print bill
            boolean complete = txtBILL.print();
            
            if(complete){
            JOptionPane.showMessageDialog(null, "Impression faite!","Message",JOptionPane.INFORMATION_MESSAGE);
            }else{
             JOptionPane.showMessageDialog(null, "Impression en cours...!","Imprimante",JOptionPane.ERROR_MESSAGE);
            }
        } catch (PrinterException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
            
        
    }//GEN-LAST:event_btnPRINTBILLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Commande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Commande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Commande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Commande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Commande().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnADDCOMMANDE;
    private javax.swing.JButton btnCREATEBILL;
    private javax.swing.JButton btnPRINTBILL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenuAdminUser;
    private javax.swing.JMenu jMenuAdminUser1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemAddCommande;
    private javax.swing.JMenuItem jMenuItemAddCommande2;
    private javax.swing.JMenuItem jMenuItemAddFournisseur;
    private javax.swing.JMenuItem jMenuItemAddFournisseur2;
    private javax.swing.JMenuItem jMenuItemManageClient;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tableCLIENT;
    private javax.swing.JTable tableCOMMANDE;
    private javax.swing.JTable tablePRODUIT;
    private javax.swing.JTextArea txtBILL;
    private javax.swing.JTextField txtDESCRIPTIFCLIENT;
    private javax.swing.JTextField txtDESIGNATIONCLIENT;
    private javax.swing.JTextField txtFRAISPORT;
    private javax.swing.JTextField txtNOMCLIENT;
    private javax.swing.JTextField txtPRENOMCLIENT;
    private javax.swing.JTextField txtPRIXTHTCCLIENT;
    private javax.swing.JTextField txtPRIXTTCCLIENT;
    private javax.swing.JTextField txtPRIXUHTCLIENT;
    private javax.swing.JTextField txtQTECLIENT;
    private javax.swing.JTextField txtREFCLIENT;
    private javax.swing.JTextField txtTVACLIENT;
    // End of variables declaration//GEN-END:variables
}
